# Generated by Django 4.2 on 2023-06-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_schedule_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
