# Generated by Django 4.2 on 2023-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_question_author_remove_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='diary',
            field=models.IntegerField(),
        ),
    ]
