# Generated by Django 4.2 on 2023-06-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_schedule_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='diary',
        ),
    ]
