# Generated by Django 4.2 on 2023-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='연인의 이메일 주소'),
        ),
    ]
