# Generated by Django 4.2 on 2023-06-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.DateTimeField(default='2023-01-12', verbose_name='우리가 처음 사귀게 된 날'),
            preserve_default=False,
        ),
    ]
